sudo: false
language: python
python:
- '2.7'
install:
- pip uninstall -y pytest py
- pip install .
- pip install python-coveralls
script:
- python setup.py test --addopts \'--cov=wamopacker\'
after_success:
- coveralls
