---
vm_name: base
vm_version: 1.0.0
include:
  - ssh_key_name.yml
upload_ssh_key_file: (( env|HOME ))/.ssh/(( ssh_key_name ))
ssh_user: ubuntu
ssh_password: ubuntu
virtualbox_iso_url: http://releases.ubuntu.com/trusty/ubuntu-14.04.3-server-amd64.iso
virtualbox_iso_checksum: 9e5fecc94b3925bededed0fdca1bd417
virtualbox_output_directory: output/base/virtualbox
virtualbox_output_name: (( vm_name ))
aws_region: eu-west-1
aws_instance_type: t2.nano
aws_ami_id: ami-8d16ccfe
aws_ami_force_deregister: true
provisioners:
  - type: shell
    scripts:
      - scripts/apt-get_upgrade.sh
      - scripts/virtualbox_guest_additions.sh
      - scripts/remove_udev_persistent_net_rules.sh
    execute_command: (( shell_command_sudo ))
  - type: shell
    scripts:
      - scripts/passwordless_sudo.sh
      - scripts/lock_password.sh
    environment_vars:
      - SETUP_USER_ACCOUNT=(( ssh_user ))
    execute_command: (( shell_command_sudo ))
  - type: file
    source: (( upload_ssh_key_file )).pub
    destination: /tmp/(( ssh_key_name )).pub
  - type: shell
    scripts:
      - scripts/set_ssh_authorized_key.sh
    environment_vars:
      - SSH_PUBLIC_KEY_FILES=/tmp/(( ssh_key_name )).pub
vagrant: true
vagrant_output: output/base/(( vm_name ))_{{ .Provider }}.box
vagrant_publish_url_prefix: file://(( env | PWD ))/output/
vagrant_publish_copy_command: cp (( FILE_PATH )) (( env | PWD ))/output/(( FILE_NAME ))
vagrant_uninstall_outdated_box: true
