---
vm_name: base
include:
  - ssh_key_name.yml
ssh_key_file: (( env|HOME ))/.ssh/(( ssh_key_name ))
virtualbox_user: ubuntu
virtualbox_password: ubuntu
virtualbox_iso_url: http://releases.ubuntu.com/trusty/ubuntu-14.04.3-server-amd64.iso
virtualbox_iso_checksum: 9e5fecc94b3925bededed0fdca1bd417
virtualbox_output_directory: base/virtualbox
virtualbox_ovf_output: (( vm_name ))
aws_user: ubuntu
aws_region: eu-west-1
aws_ami_id: ami-8d16ccfe
aws_instance_type: t2.micro
provisioners:
  - type: shell
    scripts:
      - scripts/apt-get_upgrade.sh
      - scripts/virtualbox_guest_additions.sh
      - scripts/remove_udev_persistent_net_rules.sh
    execute_command: (( shell_command_sudo ))
  - type: shell
    scripts:
      - scripts/passwordless_sudo.sh
      - scripts/lock_password.sh
    environment_vars:
      - SETUP_USER_ACCOUNT=(( virtualbox_user ))
    execute_command: (( shell_command_sudo ))
  - type: file
    source: (( ssh_key_file )).pub
    destination: /tmp/(( ssh_key_name )).pub
  - type: shell
    scripts:
      - scripts/set_ssh_authorized_key.sh
    environment_vars:
      - SSH_PUBLIC_KEY_FILES=/tmp/(( ssh_key_name )).pub
vagrant: true
vagrant_output: base/(( vm_name ))_{{ .Provider }}.box
vagrant_keep_inputs: true
